"""tabla pagos

Revision ID: 230d44a30c5a
Revises: 0ca73ad011a9
Create Date: 2026-06-18 17:28:19.558805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '230d44a30c5a'
down_revision = '0ca73ad011a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pagos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('metodo_pago', sa.String(length=50), nullable=False),
    sa.Column('fecha_pago', sa.Date(), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('reserva_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['reserva_id'], ['reservas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pagos')
    # ### end Alembic commands ###
