"""tabla paquetes

Revision ID: 447d1460d921
Revises: 1a8153ae437f
Create Date: 2026-06-18 16:58:16.257423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '447d1460d921'
down_revision = '1a8153ae437f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paquetes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('precio', sa.Float(), nullable=False),
    sa.Column('duracion', sa.String(length=50), nullable=True),
    sa.Column('destino_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['destino_id'], ['destinos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('paquetes')
    # ### end Alembic commands ###
