"""tabla facturas

Revision ID: aae0e9ce4478
Revises: 230d44a30c5a
Create Date: 2026-06-21 19:45:54.869362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aae0e9ce4478'
down_revision = '230d44a30c5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facturas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=50), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('pago_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pago_id'], ['pagos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('facturas')
    # ### end Alembic commands ###
